import { useState, useEffect } from 'react';
import api, { parentAPI } from '../../services/api';
import { toast } from 'react-toastify';
import axios from 'axios';
import { 
  FileText, 
  Download, 
  BarChart3, 
  Users, 
  TrendingUp, 
  Search,
  MessageSquare,
  LayoutDashboard
} from 'lucide-react';
import { Card, Button, Select, Spin, Empty, Tag, Divider } from 'antd';

const ParentReports = () => {
  const [children, setChildren] = useState([]);
  const [selectedChildId, setSelectedChildId] = useState(null);
  const [report, setReport] = useState('');
  const [isGenerating, setIsGenerating] = useState(false);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchChildren();
  }, []);

  const fetchChildren = async () => {
    try {
      setLoading(true);
      const response = await parentAPI.getChildrenOverview();
      const childrenData = response.data.data.children;
      setChildren(childrenData);
      if (childrenData.length > 0) {
        setSelectedChildId(childrenData[0].userId || childrenData[0].id);
      }
    } catch (error) {
      console.error('Error fetching children:', error);
      toast.error('Failed to load children list');
    } finally {
      setLoading(false);
    }
  };

  const handleGenerateReport = async () => {
    if (!selectedChildId) {
      toast.error('Please select a child to generate report');
      return;
    }

    setIsGenerating(true);
    setReport('');
    try {
      // The backend uses generateStudentReport controller which expects a User ID
      const res = await api.get(`/reports/user/${selectedChildId}`);
      setReport(res.data.report);
      toast.success('Performance report generated successfully');
    } catch (error) {
      console.error('Error generating report:', error);
      toast.error('Failed to generate performance report');
    } finally {
      setIsGenerating(false);
    }
  };

  const handleDownloadPDF = () => {
    if (!report) return;
    
    // Simple way to print the report
    const printWindow = window.open('', '_blank');
    const child = children.find(c => c.id === selectedChildId);
    
    printWindow.document.write(`
      <html>
        <head>
          <title>Progress Report - ${child?.fullName}</title>
          <style>
            body { font-family: 'Inter', sans-serif; padding: 40px; color: #1e293b; line-height: 1.6; }
            h1 { color: #2563eb; border-bottom: 2px solid #e2e8f0; padding-bottom: 10px; }
            .meta { margin-bottom: 30px; color: #64748b; }
            .content { white-space: pre-wrap; background: #f8fafc; padding: 25px; border-radius: 8px; border-left: 4px solid #2563eb; }
          </style>
        </head>
        <body>
          <h1>EduCloud Progress Report</h1>
          <div class="meta">
            <p><strong>Student:</strong> ${child?.fullName}</p>
            <p><strong>Class:</strong> ${child?.class}</p>
            <p><strong>Date:</strong> ${new Date().toLocaleDateString()}</p>
          </div>
          <div class="content">${report}</div>
          <footer style="margin-top: 50px; text-align: center; font-size: 0.8rem; color: #94a3b8;">
            Generated by EduCloud AI System • Confidential Document
          </footer>
        </body>
      </html>
    `);
    printWindow.document.close();
    setTimeout(() => {
      printWindow.print();
      printWindow.close();
    }, 250);
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <Spin size="large" tip="Loading data..." />
      </div>
    );
  }

  return (
    <div className="max-w-6xl mx-auto p-4 md:p-8 space-y-8">
      {/* Header */}
      <div className="bg-white/80 backdrop-blur-md p-8 rounded-3xl shadow-sm border border-white/50 flex flex-col md:flex-row justify-between items-center gap-6">
        <div className="flex items-center gap-4">
          <div className="p-4 bg-blue-600 rounded-2xl shadow-lg shadow-blue-200">
            <FileText className="w-8 h-8 text-white" />
          </div>
          <div>
            <h1 className="text-3xl font-black text-slate-800 tracking-tight">AI Progress Reports</h1>
            <p className="text-slate-500 font-medium italic">Powered by EduCloud Intelligence</p>
          </div>
        </div>
        
        {children.length > 1 ? (
          <div className="flex items-center gap-3 bg-slate-50 p-2 rounded-2xl border border-slate-200">
            <span className="pl-4 text-xs font-black text-slate-400 uppercase">Child</span>
            <Select
              value={selectedChildId}
              onChange={setSelectedChildId}
              className="w-48 monitoring-select"
              variant="borderless"
              options={children.map(c => ({ label: c.fullName, value: c.userId || c.id }))}
            />
          </div>
        ) : children.length === 1 ? (
          <div className="px-6 py-2 bg-blue-50 border border-blue-100 rounded-2xl">
            <span className="text-xs font-black text-blue-400 uppercase block mb-0.5">Monitoring</span>
            <span className="text-sm font-bold text-blue-800">{children[0].fullName}</span>
          </div>
        ) : null}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
        {/* Left: Controls */}
        <div className="lg:col-span-1 space-y-6">
          <Card className="rounded-[2rem] shadow-xl border-0 overflow-hidden hover-lift">
            <div className="p-2">
              <div className="bg-gradient-to-br from-blue-600 to-indigo-700 p-6 rounded-[1.5rem] text-white">
                <LayoutDashboard className="w-6 h-6 mb-4 opacity-50" />
                <h3 className="text-xl font-bold mb-2">Performance Analysis</h3>
                <p className="text-blue-100 text-sm leading-relaxed">
                  Our AI engine will analyze your child's exam scores, attendance patterns, and teacher behavioral feedback to generate a comprehensive study strategy.
                </p>
              </div>
              
              <div className="p-6 space-y-6">
                <div className="flex items-center gap-4 text-slate-600">
                  <div className="w-2 h-2 rounded-full bg-green-500" />
                  <span className="text-sm font-bold uppercase tracking-widest">Score Trends</span>
                </div>
                <div className="flex items-center gap-4 text-slate-600">
                  <div className="w-2 h-2 rounded-full bg-purple-500" />
                  <span className="text-sm font-bold uppercase tracking-widest">Attendance Density</span>
                </div>
                <div className="flex items-center gap-4 text-slate-600">
                  <div className="w-2 h-2 rounded-full bg-orange-500" />
                  <span className="text-sm font-bold uppercase tracking-widest">Teacher Insights</span>
                </div>

                <Divider />

                <Button 
                  type="primary" 
                  size="large" 
                  block 
                  icon={<BarChart3 className="w-4 h-4" />}
                  onClick={handleGenerateReport}
                  loading={isGenerating}
                  className="rounded-xl h-14 font-black shadow-lg shadow-blue-200"
                >
                  {isGenerating ? 'ANALYZING...' : 'GENERATE AI REPORT'}
                </Button>
              </div>
            </div>
          </Card>

          <Card className="rounded-[2rem] shadow-lg border-0 bg-slate-900 text-white">
            <div className="flex items-start gap-4">
              <MessageSquare className="w-6 h-6 text-blue-400" />
              <div>
                <h4 className="font-bold text-white mb-1">Need Clarification?</h4>
                <p className="text-white/50 text-sm">You can contact teachers directly if you have questions about the report findings.</p>
              </div>
            </div>
          </Card>
        </div>

        {/* Right: Output */}
        <div className="lg:col-span-2">
          {isGenerating ? (
            <Card className="rounded-[2rem] shadow-xl border-0 h-full flex flex-col items-center justify-center p-20 bg-white/50">
               <Spin size="large" />
               <h3 className="mt-8 font-black text-slate-800 text-xl text-center">
                 AI is analyzing thousands of data points for ${children.find(c => c.id === selectedChildId)?.fullName}...
               </h3>
               <p className="text-slate-400 mt-2">This usually takes 5-10 seconds</p>
            </Card>
          ) : report ? (
            <div className="animate-in fade-in slide-in-from-right-4 duration-700">
              <Card 
                className="rounded-[2rem] shadow-2xl border-0 overflow-hidden"
                title={
                  <div className="flex items-center justify-between w-full py-4">
                    <div className="flex items-center gap-3">
                      <TrendingUp className="w-5 h-5 text-green-500" />
                      <span className="font-black text-slate-800 text-lg uppercase tracking-tight">System Analysis Results</span>
                    </div>
                    <Button 
                      icon={<Download className="w-4 h-4" />} 
                      className="rounded-xl font-bold"
                      onClick={handleDownloadPDF}
                    >
                      DOWNLOAD PDF
                    </Button>
                  </div>
                }
              >
                <div className="bg-slate-50 p-8 rounded-3xl border border-slate-100 mb-6">
                  <pre className="whitespace-pre-wrap font-medium text-slate-700 leading-relaxed text-base italic font-serif">
                    {report}
                  </pre>
                </div>
                
                <div className="flex gap-4">
                  <Tag color="blue" className="rounded-full px-6 py-1 font-bold">Confidential</Tag>
                  <Tag color="green" className="rounded-full px-6 py-1 font-bold">Verified Analysis</Tag>
                </div>
              </Card>
            </div>
          ) : (
            <Card className="rounded-[2rem] shadow-xl border-dashed border-2 border-slate-200 h-full flex items-center justify-center p-20 bg-slate-50/30">
              <Empty 
                image={Empty.PRESENTED_IMAGE_SIMPLE}
                description={
                  <div className="space-y-4">
                    <h3 className="text-xl font-bold text-slate-600">No Analysis Available</h3>
                    <p className="text-slate-400 max-w-md mx-auto">
                      Please select a student and click the "Generate AI Report" button to start the deep monitoring process.
                    </p>
                  </div>
                }
              />
            </Card>
          )}
        </div>
      </div>

      <style jsx>{`
        .monitoring-select :global(.ant-select-selector) {
          background: transparent !important;
          font-weight: 800;
          color: #1e293b !important;
        }
        .hover-lift {
          transition: transform 0.3s cubic-bezier(0.34, 1.56, 0.64, 1);
        }
        .hover-lift:hover {
          transform: translateY(-8px);
        }
      `}</style>
    </div>
  );
};

export default ParentReports;
